<?php

namespace App\Services\Network;

use App\Models\Router;
use App\Models\HotspotProfile;
use App\Models\HotspotVoucher;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;
use Exception;

class HotspotService
{
    /**
     * Generate bulk vouchers on MikroTik.
     */
    public function generateVouchers(Router $router, HotspotProfile $profile, int $count): array
    {
        $vouchers = [];
        $mikrotikUsers = [];

        for ($i = 0; $i < $count; $i++) {
            $code = strtoupper(Str::random(6)); // Example: ABCD12
            // For simplicity, username = password = code
            $username = $code;
            $password = $code;

            $vouchers[] = [
                'hotspot_profile_id' => $profile->id,
                'code' => $code,
                'username' => $username,
                'password' => $password,
                'router_id' => $router->id,
                'created_by' => Auth::id(),
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ];

            $mikrotikUsers[] = [
                'name' => $username,
                'password' => $password,
                'profile' => $profile->name,
                'comment' => 'Voucher generated by ISP Dashboard - ' . now()->toDateTimeString(),
            ];
        }

        // TODO: Implement actual MikroTik API call here
        // $this->sendToMikrotik($router, $mikrotikUsers);

        // Bulk insert to DB
        HotspotVoucher::insert($vouchers);

        return $vouchers;
    }

    /**
     * Placeholder for MikroTik API call.
     */
    protected function sendToMikrotik(Router $router, array $users)
    {
        // This would use RouterOS API client
        // Example:
        // $client = new RouterosAPI();
        // $client->connect($router->ip_address, $router->username, $router->password);
        // foreach($users as $user) {
        //    $client->comm("/ip/hotspot/user/add", $user);
        // }
    }
}
